import type { CSSProperties } from 'react';
import { ArrowUpRightIcon, CheckIcon, MessageCircleIcon } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { brands, getBrand } from '../data/brands';
import { TechnicalLabel } from '../components/ui/SectionHeading';
import { MagneticButton } from '../components/ui/MagneticButton';
import { company, COMPANY_WHATSAPP_URL } from '../data/company';
import { useSeo } from '../hooks/useSeo';

export function BrandPage() {
  const { slug } = useParams();
  const brand = getBrand(slug);

  if (!brand) return <main className="flex min-h-screen items-center justify-center bg-ink-950 px-5 pt-24"><div className="text-center"><TechnicalLabel code="404" className="justify-center">Brand not found</TechnicalLabel><h1 className="mt-5 font-display text-5xl font-bold uppercase text-steel-50">No such brand</h1><Link to="/our-brands" className="mt-8 inline-flex font-mono text-[10px] uppercase tracking-tech text-signal">Back to Our Brands</Link></div></main>;

  return <BrandPageContent brand={brand} />;
}

function BrandPageContent({ brand }: { brand: typeof brands[number] }) {
  useSeo({
    title: `${brand.name === 'IKO' ? 'IKO Bearings & Linear Motion Products' : brand.name === 'WON ST' ? 'WON Linear Motion Products' : 'STIEBER Freewheels & Backstops'}`,
    description: brand.name === 'IKO' ? 'KHS-LG supplies IKO precision bearings and linear motion products for industrial, automation and precision machinery applications.' : brand.name === 'WON ST' ? 'KHS-LG supplies WON ST linear motion products including bearings, shafts, guideways and motion components for industrial automation.' : 'KHS-LG supplies STIEBER freewheels, overrunning clutches and backstop solutions for industrial drive applications.',
    path: `/our-brands/${brand.slug}`
  });

  const quoteHref = `/contact?brand=${encodeURIComponent(brand.name)}&product=${encodeURIComponent(brand.categories[0].name)}`;
  const whatsappMessage = `Hello KHS-LG, I am looking for a ${brand.name} product. Product/Series: ______. Please assist.`;
  const accentStyle = { '--brand-accent': brand.accent, '--brand-accent-soft': brand.accentSoft } as CSSProperties;

  return (
    <main style={accentStyle}>
      <section className="relative overflow-hidden border-b border-ink-700 bg-ink-950 pb-8 pt-12 sm:pb-10 sm:pt-16 lg:pb-12 lg:pt-18">
        <div className="industrial-grid pointer-events-none absolute inset-0 opacity-30" aria-hidden />
        <div className="pointer-events-none absolute right-0 top-0 h-full w-1/2 opacity-20" style={{ background: `radial-gradient(circle at 60% 35%, ${brand.accentSoft}, transparent 55%)` }} aria-hidden />
        <div className="relative mx-auto grid w-full max-w-[1600px] items-center gap-12 px-5 sm:px-8 lg:grid-cols-[1fr_0.9fr] lg:gap-20">
          <div>
            <nav aria-label="Breadcrumb" className="font-mono text-[10px] uppercase tracking-[0.14em] text-steel-500"><Link to="/" className="hover:text-signal">Home</Link><span className="mx-2 text-ink-600">/</span><Link to="/our-brands" className="hover:text-signal">Our brands</Link><span className="mx-2 text-ink-600">/</span><span className="text-signal">{brand.name}</span></nav>
            <div className="mt-8 sm:mt-9"><TechnicalLabel code={brand.tag}>{brand.company}</TechnicalLabel><div className="mt-5 flex items-center gap-4"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: brand.accent, boxShadow: `0 0 24px ${brand.accent}` }} aria-hidden /><span className="font-mono text-[10px] uppercase tracking-tech text-steel-500">{brand.country}</span></div><h1 className="mt-4 max-w-3xl font-display text-[clamp(3.5rem,8vw,7.5rem)] font-bold uppercase leading-[0.83] text-steel-50">{brand.heroHeading[0]}<br /><span style={{ color: brand.accent }}>{brand.heroHeading[1]}</span></h1><p className="mt-5 max-w-xl text-base leading-relaxed text-steel-400">{brand.heroDescription}</p><div className="mt-8 flex flex-wrap gap-3"><MagneticButton to={quoteHref} variant="yellow">Request a Quote</MagneticButton><MagneticButton href={`${COMPANY_WHATSAPP_URL}?text=${encodeURIComponent(whatsappMessage)}`} variant="ghost" icon={<MessageCircleIcon className="h-4 w-4" aria-hidden />}>WhatsApp</MagneticButton></div></div>
          </div>
          <div className="relative mx-auto flex aspect-square w-full max-w-[560px] items-center justify-center overflow-hidden border border-ink-700 bg-ink-900 p-10">
            <div className="absolute inset-0 industrial-grid opacity-20" aria-hidden /><div className="absolute inset-12 rounded-full border" style={{ borderColor: brand.accentSoft }} aria-hidden /><div className="absolute inset-24 rounded-full border" style={{ borderColor: brand.accentSoft }} aria-hidden /><img src={brand.productImage} alt={`${brand.name} ${brand.productLabel}`} className="relative z-10 max-h-full w-full object-contain drop-shadow-[0_20px_40px_rgba(0,0,0,0.6)] transition-transform duration-700 ease-out hover:scale-105" /><span className="absolute bottom-5 left-5 font-mono text-[9px] uppercase tracking-tech text-steel-600">{brand.productLabel}</span><span className="absolute right-5 top-5 font-mono text-[9px] uppercase tracking-tech" style={{ color: brand.accent }}>KHS-LG / {brand.name}</span>
          </div>
        </div>
      </section>

      <section className="bg-ink-900 py-14 lg:py-20"><div className="mx-auto grid w-full max-w-[1400px] gap-10 px-5 sm:px-8 lg:grid-cols-[0.7fr_1.3fr] lg:gap-16"><div><TechnicalLabel code="01 / About">About {brand.name}</TechnicalLabel><h2 className="mt-5 max-w-md font-display text-4xl font-bold uppercase leading-none text-steel-50 sm:text-5xl">{brand.aboutHeading}</h2></div><div className="max-w-3xl space-y-5 text-base leading-relaxed text-steel-400">{brand.about.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></section>

      <section className="bg-ink-950 py-14 lg:py-20"><div className="mx-auto w-full max-w-[1600px] px-5 sm:px-8"><div className="flex flex-col gap-4 border-b border-ink-700 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><TechnicalLabel code="02 / Range">{brand.categoriesHeading}</TechnicalLabel><h2 className="mt-5 font-display text-4xl font-bold uppercase text-steel-50 sm:text-6xl">Built around the application.</h2></div><p className="max-w-sm text-sm leading-relaxed text-steel-500">Explore the specialist product families KHS-LG can help you source and specify.</p></div><div className="mt-8 grid gap-px border border-ink-700 bg-ink-700 md:grid-cols-2 xl:grid-cols-3">{brand.categories.map((category, index) => <article key={category.name} className="group bg-ink-950 transition-all duration-300 hover:-translate-y-1 hover:bg-ink-900"><div className="relative aspect-[1.35] overflow-hidden border-b border-ink-700 bg-ink-900"><div className="absolute inset-0 opacity-0 transition-opacity duration-300 group-hover:opacity-100" style={{ background: `radial-gradient(circle at 70% 20%, ${brand.accentSoft}, transparent 55%)` }} aria-hidden /><img src={category.image} alt="" className="relative h-full w-full object-contain p-8 transition-transform duration-500 group-hover:scale-105" /><span className="absolute left-5 top-5 font-mono text-[9px] tracking-tech" style={{ color: brand.accent }}>{String(index + 1).padStart(2, '0')}</span></div><div className="p-6"><h3 className="font-display text-2xl font-semibold uppercase text-steel-50 group-hover:text-[var(--brand-accent)]">{category.name}</h3><p className="mt-3 min-h-12 text-sm leading-relaxed text-steel-500">{category.description}</p><Link to={`${quoteHref}&category=${encodeURIComponent(category.name)}`} className="mt-6 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-tech text-steel-400 transition-colors group-hover:text-[var(--brand-accent)]">Request a quote <ArrowUpRightIcon className="h-3.5 w-3.5 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" aria-hidden /></Link></div></article>)}</div></div></section>

      <section className="relative overflow-hidden border-y border-ink-700 bg-ink-900 py-14 lg:py-20"><div className="industrial-grid pointer-events-none absolute inset-0 opacity-15" aria-hidden /><div className="relative mx-auto w-full max-w-[1600px] px-5 sm:px-8"><TechnicalLabel code="03 / Engineering">{brand.whyHeading}</TechnicalLabel><div className="mt-8 grid gap-px border border-ink-700 bg-ink-700 md:grid-cols-2 xl:grid-cols-3">{brand.features.map((feature, index) => <article key={feature.title} className="bg-ink-950 p-6 sm:p-8"><div className="flex items-start justify-between"><span className="flex h-8 w-8 items-center justify-center border" style={{ borderColor: brand.accentSoft }}><CheckIcon className="h-4 w-4" style={{ color: brand.accent }} aria-hidden /></span><span className="font-mono text-[9px] tracking-tech text-steel-600">0{index + 1}</span></div><h3 className="mt-10 font-display text-xl font-semibold uppercase text-steel-50">{feature.title}</h3><p className="mt-3 text-sm leading-relaxed text-steel-500">{feature.description}</p></article>)}</div></div></section>

      <section className="bg-ink-950 py-14 lg:py-20"><div className="mx-auto grid w-full max-w-[1400px] items-center gap-10 px-5 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:gap-12"><div className="relative aspect-[4/3] overflow-hidden border border-ink-700 bg-ink-900"><div className="absolute inset-0 industrial-grid opacity-20" aria-hidden /><img src={brand.applicationImage} alt={`${brand.name} application component`} className="relative h-full w-full object-contain p-10 transition-transform duration-700 hover:scale-105" /><span className="absolute bottom-4 left-4 font-mono text-[9px] uppercase tracking-tech text-steel-600">{brand.name} / application focus</span></div><div><TechnicalLabel code="04 / Applications">{brand.applicationsHeading}</TechnicalLabel><h2 className="mt-5 font-display text-4xl font-bold uppercase text-steel-50 sm:text-6xl">Motion, specified.</h2><ul className="mt-8 grid gap-x-8 gap-y-4 sm:grid-cols-2">{brand.applications.map((application) => <li key={application} className="flex items-center gap-3 border-b border-ink-700 pb-3 font-display text-base font-semibold uppercase text-steel-300"><span className="h-1.5 w-1.5 shrink-0" style={{ backgroundColor: brand.accent }} aria-hidden />{application}</li>)}</ul></div></div></section>

      <section className="relative overflow-hidden border-t border-ink-700 bg-ink-950 py-16 lg:py-24"><div className="industrial-grid pointer-events-none absolute inset-0 opacity-20" aria-hidden /><div className="relative mx-auto w-full max-w-[1100px] px-5 text-center sm:px-8"><TechnicalLabel code="05 / Next step" className="justify-center">Talk to KHS-LG about {brand.name}</TechnicalLabel><h2 className="mx-auto mt-6 max-w-4xl font-display text-[clamp(2.8rem,7vw,6.5rem)] font-bold uppercase leading-[0.88] text-steel-50">{brand.ctaHeading}</h2><p className="mx-auto mt-7 max-w-2xl text-base leading-relaxed text-steel-400">{brand.ctaDescription}</p><div className="mt-10 flex flex-wrap justify-center gap-3"><MagneticButton to={quoteHref} variant="yellow">Request a Quote</MagneticButton><MagneticButton href={`${COMPANY_WHATSAPP_URL}?text=${encodeURIComponent(whatsappMessage)}`} variant="ghost" icon={<MessageCircleIcon className="h-4 w-4" aria-hidden />}>Send part number on WhatsApp</MagneticButton></div><p className="mt-7 font-mono text-[10px] uppercase tracking-tech text-steel-600">{company.email} · {company.phone}</p></div></section>

      <section className="border-t border-ink-700 bg-ink-900 py-16"><div className="mx-auto w-full max-w-[1400px] px-5 sm:px-8"><TechnicalLabel code="Explore other brands">Continue through the portfolio</TechnicalLabel><div className="mt-6 grid gap-px border border-ink-700 bg-ink-700 md:grid-cols-3">{brands.filter((item) => item.slug !== brand.slug).map((item) => <Link key={item.slug} to={`/our-brands/${item.slug}`} className="group flex items-center justify-between bg-ink-950 p-6 hover:bg-ink-900"><span><strong className="block font-display text-2xl uppercase text-steel-50 group-hover:text-[var(--brand-accent)]" style={{ '--brand-accent': item.accent } as CSSProperties}>{item.name}</strong><small className="font-mono text-[9px] uppercase tracking-tech text-steel-600">{item.tag}</small></span><ArrowUpRightIcon className="h-4 w-4 text-steel-600 group-hover:text-signal" aria-hidden /></Link>)}</div></div></section>
    </main>
  );
}
