import { ActivityIcon, ArrowRightIcon, CheckCircle2Icon, DraftingCompassIcon, FileCheck2Icon, RefreshCwIcon, RulerIcon, ScanLineIcon } from 'lucide-react';
import { PageHero } from '../components/layout/PageHero';
import { QualityVisual } from '../components/sections/QualityVisual';
import { MagneticButton } from '../components/ui/MagneticButton';
import { Reveal, RevealText } from '../components/ui/RevealText';
import { TechnicalLabel } from '../components/ui/SectionHeading';
import { company } from '../data/company';
import { qualityApplicationFlow, qualityCapabilities, qualityImprovement, qualityProcess } from '../data/quality';
import { useSeo } from '../hooks/useSeo';

const CAPABILITY_ICONS = [DraftingCompassIcon, RulerIcon, FileCheck2Icon, ScanLineIcon, ActivityIcon, RefreshCwIcon, FileCheck2Icon, CheckCircle2Icon];

export function Quality() {
  useSeo({ title: 'Quality', description: 'KHS-LG quality is built through engineering review, inspection, performance evaluation and continual improvement. ISO 9001:2015.', path: '/quality' });

  return <main>
    <PageHero code="Quality assurance" eyebrow={`${company.certification} · Engineering quality`} lines={['Engineered for', 'precision.']} body="Quality at KHS-LG is a connected discipline: understand the application, control the details, verify the result and keep learning from every requirement." breadcrumb={[{ label: 'Home', to: '/' }, { label: 'Quality' }]} />

    <section className="border-b border-ink-700 bg-ink-900 py-12 lg:py-18" aria-label="Quality assurance introduction">
      <div className="mx-auto grid w-full max-w-[1600px] gap-12 px-5 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:gap-20">
        <Reveal><TechnicalLabel code="01 / Quality assurance">Precision is a process</TechnicalLabel><RevealText as="h2" lines={['Quality is not', 'a final check.']} accentLast className="mt-5 text-[clamp(2.6rem,5vw,5rem)] font-bold text-steel-50" /><p className="mt-7 max-w-xl text-[15px] leading-relaxed text-steel-400">A dependable bearing starts with the right questions. KHS-LG considers customer requirements, application conditions, product consistency, inspection evidence and delivery expectations as part of one quality conversation.</p><div className="mt-8 flex flex-wrap gap-3 font-mono text-[9px] uppercase tracking-tech text-steel-500"><span className="border border-ink-600 px-3 py-2">Requirement-led</span><span className="border border-ink-600 px-3 py-2">Evidence-based</span><span className="border border-ink-600 px-3 py-2">Customer-focused</span></div></Reveal>
        <QualityVisual mode="hero" />
      </div>
    </section>

    <section className="border-b border-ink-700 bg-ink-950 py-12 lg:py-18" aria-labelledby="engineering-heading">
      <div className="mx-auto grid w-full max-w-[1600px] gap-12 px-5 sm:px-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:gap-20">
        <QualityVisual mode="engineering" />
        <Reveal><TechnicalLabel code="02 / Engineering & design">Technical evaluation before execution</TechnicalLabel><h2 id="engineering-heading" className="mt-5 font-display text-4xl font-bold uppercase leading-[0.9] text-steel-50 sm:text-6xl">Design with the <span className="text-signal">application</span> in view.</h2><p className="mt-7 text-[15px] leading-relaxed text-steel-400">Our technical approach connects bearing geometry with the duty it must perform. CAD-based workflows, 3D modelling, stress analysis, design review, verification and reverse-engineering methods can help turn an application requirement into a clearer technical decision.</p><p className="mt-5 text-[15px] leading-relaxed text-steel-500">The objective is practical: understand the load, speed, environment and fit well enough to select a bearing solution that makes sense in the machine.</p></Reveal>
      </div>
    </section>

    <section className="border-b border-ink-700 bg-ink-900 py-12 lg:py-18" aria-labelledby="inspection-heading">
      <div className="mx-auto grid w-full max-w-[1600px] gap-12 px-5 sm:px-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-center lg:gap-20">
        <Reveal><TechnicalLabel code="03 / Precision inspection">Make the invisible measurable</TechnicalLabel><h2 id="inspection-heading" className="mt-5 font-display text-4xl font-bold uppercase leading-[0.9] text-steel-50 sm:text-6xl">Precision lives in the <span className="text-signal">details.</span></h2><p className="mt-7 text-[15px] leading-relaxed text-steel-400">Dimensional accuracy, geometry, surface condition and component consistency all influence bearing behavior. Inspection thinking therefore follows the product through the details that matter, from form and profile review to visual and process verification.</p><div className="mt-8 border-l border-signal pl-5 font-mono text-[10px] uppercase leading-relaxed tracking-tech text-steel-500">No invented numbers. The right evidence depends on the product, specification and application.</div></Reveal>
        <QualityVisual mode="inspection" />
      </div>
    </section>

    <section className="border-b border-ink-700 bg-ink-950 py-12 lg:py-18" aria-labelledby="testing-heading">
      <div className="mx-auto w-full max-w-[1600px] px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><Reveal><TechnicalLabel code="04 / Testing & performance">Verification follows the requirement</TechnicalLabel><h2 id="testing-heading" className="mt-5 font-display text-4xl font-bold uppercase leading-[0.9] text-steel-50 sm:text-6xl">Rotation becomes <span className="text-signal">evidence.</span></h2></Reveal><Reveal delay={0.1}><p className="max-w-2xl text-[15px] leading-relaxed text-steel-400">Performance evaluation can include load-related review, dimensional verification, rotational behavior, noise and vibration checks, and reliability considerations matched to the operating conditions. The result is a clearer quality decision, not an unsupported promise.</p></Reveal></div><div className="mt-12 grid gap-px border border-ink-700 bg-ink-700 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr]"><TestNode title="Bearing" detail="Defined requirement" /><ArrowRightIcon className="hidden self-center bg-ink-950 p-3 text-signal md:block" aria-hidden /><TestNode title="Rotation" detail="Controlled behavior" /><ArrowRightIcon className="hidden self-center bg-ink-950 p-3 text-signal md:block" aria-hidden /><TestNode title="Sensor" detail="Measured response" /><ArrowRightIcon className="hidden self-center bg-ink-950 p-3 text-signal md:block" aria-hidden /><TestNode title="Verification" detail="Quality decision" /></div></div>
    </section>

    <section className="border-b border-ink-700 bg-ink-900 py-12 lg:py-18" aria-labelledby="process-heading">
      <div className="mx-auto w-full max-w-[1600px] px-5 sm:px-8"><TechnicalLabel code="05 / Quality control framework">From engineering to delivery</TechnicalLabel><div className="mt-5 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><h2 id="process-heading" className="font-display text-4xl font-bold uppercase leading-[0.9] text-steel-50 sm:text-6xl">A connected <span className="text-signal">quality path.</span></h2><p className="max-w-md text-[15px] leading-relaxed text-steel-500">This framework describes how quality decisions can be connected across a supply journey. It is a guide for control and communication, not a claim that every product follows one identical manufacturing route.</p></div><ol className="quality-process-line mt-12 grid gap-px border border-ink-700 bg-ink-700 md:grid-cols-2 lg:grid-cols-6">{qualityProcess.map((step, index) => <li key={step.code} className="relative bg-ink-950 p-6"><Reveal delay={index * 0.04}><span className="font-display text-3xl font-bold text-signal">{step.code}</span><h3 className="mt-5 break-words font-display text-xl font-semibold uppercase tracking-[0.1em] text-steel-50">{step.title}</h3><p className="mt-3 text-sm leading-relaxed text-steel-500">{step.body}</p></Reveal></li>)}</ol></div>
    </section>

    <section className="border-b border-ink-700 bg-ink-950 py-12 lg:py-18" aria-labelledby="improvement-heading">
      <div className="mx-auto grid w-full max-w-[1600px] gap-12 px-5 sm:px-8 lg:grid-cols-[1fr_1fr] lg:items-center lg:gap-24"><Reveal><TechnicalLabel code="06 / Continuous improvement">Feedback that moves the system forward</TechnicalLabel><h2 id="improvement-heading" className="mt-5 font-display text-4xl font-bold uppercase leading-[0.9] text-steel-50 sm:text-6xl">Plan. Check. <span className="text-signal">Improve.</span></h2><p className="mt-7 max-w-xl text-[15px] leading-relaxed text-steel-400">Monitoring, customer feedback, corrective action and preventive thinking help turn a quality event into technical learning. Continual improvement is the discipline of checking whether the process is effective, then making the next decision stronger.</p></Reveal><div className="relative mx-auto aspect-square w-full max-w-[430px] rounded-full border border-ink-600 p-10 sm:p-14"><div className="quality-orbit absolute inset-5 rounded-full border border-signal/30" aria-hidden /><div className="relative grid h-full grid-cols-2 grid-rows-2 gap-px overflow-hidden border border-ink-700 bg-ink-700">{qualityImprovement.map((step) => <div key={step.code} className="bg-ink-950 p-4 sm:p-6"><span className="font-mono text-[9px] tracking-tech text-signal">{step.code}</span><h3 className="mt-3 font-display text-lg font-semibold uppercase text-steel-50">{step.title}</h3><p className="mt-2 hidden text-xs leading-relaxed text-steel-500 sm:block">{step.body}</p></div>)}</div></div></div>
    </section>

    <section className="border-b border-ink-700 bg-ink-900 py-12 lg:py-18" aria-labelledby="application-heading">
      <div className="mx-auto w-full max-w-[1600px] px-5 sm:px-8"><div className="max-w-3xl"><TechnicalLabel code="07 / Customer-centric quality">Start with the machine, not the catalogue</TechnicalLabel><h2 id="application-heading" className="mt-5 font-display text-4xl font-bold uppercase leading-[0.9] text-steel-50 sm:text-6xl">Quality starts with <span className="text-signal">understanding</span> the application.</h2><p className="mt-7 text-[15px] leading-relaxed text-steel-400">Load, speed, temperature, lubrication, mounting, duty cycle and operating environment shape the right bearing choice. KHS-LG brings that application context into the technical conversation so selection and quality verification are connected to the work the bearing must do.</p></div><div className="mt-12 grid gap-px border border-ink-700 bg-ink-700 md:grid-cols-5">{qualityApplicationFlow.map((step, index) => <div key={step} className="relative bg-ink-950 p-6"><span className="font-mono text-[9px] tracking-tech text-signal">0{index + 1}</span><p className="mt-5 font-display text-lg font-semibold uppercase leading-tight text-steel-50">{step}</p>{index < qualityApplicationFlow.length - 1 && <ArrowRightIcon className="mt-5 h-4 w-4 text-steel-600 md:absolute md:right-3 md:top-1/2 md:mt-0" aria-hidden />}</div>)}</div></div>
    </section>

    <section className="border-b border-ink-700 bg-ink-950 py-12 lg:py-18" aria-labelledby="capabilities-heading">
      <div className="mx-auto w-full max-w-[1600px] px-5 sm:px-8"><TechnicalLabel code="08 / Quality capabilities">Technical discipline in practice</TechnicalLabel><h2 id="capabilities-heading" className="mt-5 font-display text-4xl font-bold uppercase leading-[0.9] text-steel-50 sm:text-6xl">Built around <span className="text-signal">evidence.</span></h2><div className="mt-12 grid gap-px border border-ink-700 bg-ink-700 sm:grid-cols-2 xl:grid-cols-4">{qualityCapabilities.map(([title, body], index) => { const Icon = CAPABILITY_ICONS[index]; return <Reveal key={title} delay={index * 0.03} className="bg-ink-950 p-6 transition-colors hover:bg-ink-800 sm:p-7"><Icon className="h-5 w-5 text-signal" aria-hidden /><h3 className="mt-8 font-display text-xl font-semibold uppercase leading-tight text-steel-50">{title}</h3><p className="mt-3 text-sm leading-relaxed text-steel-500">{body}</p></Reveal>; })}</div></div>
    </section>

    <section className="border-b border-ink-700 bg-ink-900 py-12 lg:py-18" aria-labelledby="certification-heading"><div className="mx-auto grid w-full max-w-[1600px] gap-10 px-5 sm:px-8 lg:grid-cols-[1fr_0.8fr] lg:items-center lg:gap-16"><Reveal><TechnicalLabel code="09 / Certifications & standards">Verified quality management</TechnicalLabel><h2 id="certification-heading" className="mt-5 font-display text-4xl font-bold uppercase leading-[0.9] text-steel-50 sm:text-6xl">A standard for <span className="text-signal">consistency.</span></h2><p className="mt-7 max-w-xl text-[15px] leading-relaxed text-steel-400">KHS-LG references ISO 9001:2015 as its quality management standard. The certification is part of a broader commitment to documented, repeatable and customer-focused quality practices.</p></Reveal><div className="border border-signal/60 bg-ink-950 p-8 sm:p-10"><div className="flex items-start justify-between gap-5"><CheckCircle2Icon className="h-8 w-8 text-signal" aria-hidden /><span className="font-mono text-[9px] uppercase tracking-tech text-steel-500">Verified reference</span></div><p className="mt-12 font-mono text-[10px] uppercase tracking-tech text-signal">Quality management system</p><p className="mt-4 font-display text-4xl font-bold uppercase text-steel-50">{company.certification}</p><p className="mt-5 text-sm leading-relaxed text-steel-500">A clear framework for process discipline, customer requirements and continual improvement.</p></div></div></section>

    <section className="relative overflow-hidden border-b border-ink-700 bg-ink-950 py-24 lg:py-32" aria-label="Quality promise"><div className="industrial-grid pointer-events-none absolute inset-0 opacity-20" aria-hidden /><div className="relative mx-auto w-full max-w-[1600px] px-5 text-center sm:px-8"><TechnicalLabel code="10 / KHS-LG quality promise" className="justify-center">Quality that supports every rotation</TechnicalLabel><RevealText as="h2" lines={['Precision that earns', 'customer confidence.']} accentLast className="mx-auto mt-6 max-w-5xl text-[clamp(2.8rem,8vw,7rem)] font-bold text-steel-50" /><Reveal><p className="mx-auto mt-8 max-w-xl text-[15px] leading-relaxed text-steel-400">Tell us about the load, speed and environment behind your requirement. Our team can help connect the application to the right bearing conversation.</p><div className="mt-10"><MagneticButton to="/contact" variant="yellow">Discuss your requirement <ArrowRightIcon className="h-4 w-4" aria-hidden /></MagneticButton></div></Reveal></div></section>
  </main>;
}

function TestNode({ title, detail }: { title: string; detail: string }) {
  return <div className="bg-ink-950 p-6"><span className="font-mono text-[9px] uppercase tracking-tech text-signal">Quality signal</span><h3 className="mt-5 font-display text-xl font-semibold uppercase text-steel-50">{title}</h3><p className="mt-2 text-sm text-steel-500">{detail}</p></div>;
}